# MOD-12930 — balanced full suite

Same contenders and axes as the main (imbalanced) suite, but the text query of every
(size, depth) cell is **calibrated** so the SEARCH mirror's p50 matches the VSIM mirror's
(±20%, geometric bisection on the target match count; the achieved ratio is recorded).

**Why balance:** with skewed branches, `hybrid ≈ max + C` and `hybrid ≈ sum + C'` fit the
same measurement (sum − max = the small branch ≈ noise), so neither concurrency nor
overhead is identifiable. Equal branches maximize sum − max, so the w0/w6 pair separates
"branches overlap" from "serial overhead C" and yields C twice, independently.

**Matrix:** size (10K/100K/500K) × depth K/W (10/20, 100/200, 1000/2000 — giving the
C(WINDOW) curve) × workers (0/6) × fields (none/title+text) × 4 contenders.
Note: at 10K × depth 1000/2000 balance is unreachable (text maxes out below the vector
branch) — the cell runs anyway with `balanced=False` and its ratio recorded.

In [1]:
import json
import pandas as pd
import bench_lib as B
import balanced_lib as BAL

titles, texts, emb, corpus_max = B.load_data()
results, gates, meta = BAL.run_balanced_full(titles, texts, emb, corpus_max)

with open('results_balanced_full.json', 'w') as f:
    json.dump(dict(meta=meta, results=results, gates=gates), f, indent=2, default=str)
pd.DataFrame(results).to_csv('results_balanced_full.csv', index=False)
print('saved results_balanced_full.json / .csv')

===== balanced full, dataset size 10000 =====

loaded+indexed 10000 docs in 0.6s (hash_indexing_failures=0)
n=10000 k/w=10/20: vsim p50=0.19ms — calibrating
  target≈447 -> search p50 0.14ms

  target≈2,115 -> search p50 0.21ms
  -> |matches|≈2,469 ratio=1.08 balanced=True
{'size': 10000, 'k': 10, 'window': 20, 'matches_mean': 2469.375, 'balance_ratio': 1.08, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=10000 k/w=10/20 w=0 fields=none       hybrid_linear  p50=0.53ms qps=  1812.5

n=10000 k/w=10/20 w=0 fields=none       hybrid_rrf     p50=0.48ms qps=  2025.4

n=10000 k/w=10/20 w=0 fields=none       search_branch  p50=0.29ms qps=  3154.1

n=10000 k/w=10/20 w=0 fields=none       vsim_branch    p50=0.15ms qps=  6355.2

n=10000 k/w=10/20 w=0 fields=title+text hybrid_linear  p50=0.57ms qps=  1722.3

n=10000 k/w=10/20 w=0 fields=title+text hybrid_rrf     p50=0.55ms qps=  1778.9

n=10000 k/w=10/20 w=0 fields=title+text search_branch  p50=0.30ms qps=  3224.7

n=10000 k/w=10/20 w=0 fields=title+text vsim_branch    p50=0.25ms qps=  4038.7

n=10000 k/w=10/20 w=6 fields=none       hybrid_linear  p50=0.39ms qps=  2491.1

n=10000 k/w=10/20 w=6 fields=none       hybrid_rrf     p50=0.42ms qps=  2277.7

n=10000 k/w=10/20 w=6 fields=none       search_branch  p50=0.30ms qps=  3105.4

n=10000 k/w=10/20 w=6 fields=none       vsim_branch    p50=0.17ms qps=  5779.0

n=10000 k/w=10/20 w=6 fields=title+text hybrid_linear  p50=0.51ms qps=  1897.6

n=10000 k/w=10/20 w=6 fields=title+text hybrid_rrf     p50=0.42ms qps=  2315.7

n=10000 k/w=10/20 w=6 fields=title+text search_branch  p50=0.36ms qps=  2722.8

n=10000 k/w=10/20 w=6 fields=title+text vsim_branch    p50=0.21ms qps=  4784.8
n=10000 k/w=100/200: vsim p50=0.33ms — calibrating
  target≈447 -> search p50 0.21ms

  target≈2,115 -> search p50 0.35ms
  -> |matches|≈2,469 ratio=1.07 balanced=True
{'size': 10000, 'k': 100, 'window': 200, 'matches_mean': 2469.375, 'balance_ratio': 1.07, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=10000 k/w=100/200 w=0 fields=none       hybrid_linear  p50=1.42ms qps=   687.6

n=10000 k/w=100/200 w=0 fields=none       hybrid_rrf     p50=1.44ms qps=   678.1

n=10000 k/w=100/200 w=0 fields=none       search_branch  p50=0.45ms qps=  2119.2

n=10000 k/w=100/200 w=0 fields=none       vsim_branch    p50=0.43ms qps=  2317.5

n=10000 k/w=100/200 w=0 fields=title+text hybrid_linear  p50=1.46ms qps=   669.8

n=10000 k/w=100/200 w=0 fields=title+text hybrid_rrf     p50=1.54ms qps=   641.2

n=10000 k/w=100/200 w=0 fields=title+text search_branch  p50=0.51ms qps=  1844.3

n=10000 k/w=100/200 w=0 fields=title+text vsim_branch    p50=0.47ms qps=  2122.0

n=10000 k/w=100/200 w=6 fields=none       hybrid_linear  p50=1.01ms qps=   958.3

n=10000 k/w=100/200 w=6 fields=none       hybrid_rrf     p50=1.01ms qps=   952.5

n=10000 k/w=100/200 w=6 fields=none       search_branch  p50=0.46ms qps=  1965.9

n=10000 k/w=100/200 w=6 fields=none       vsim_branch    p50=0.37ms qps=  2658.1

n=10000 k/w=100/200 w=6 fields=title+text hybrid_linear  p50=1.17ms qps=   837.3

n=10000 k/w=100/200 w=6 fields=title+text hybrid_rrf     p50=1.16ms qps=   842.5

n=10000 k/w=100/200 w=6 fields=title+text search_branch  p50=0.50ms qps=  1958.1

n=10000 k/w=100/200 w=6 fields=title+text vsim_branch    p50=0.43ms qps=  2260.0

n=10000 k/w=1000/2000: vsim p50=5.56ms — calibrating
  target≈447 -> search p50 0.22ms

  target≈2,115 -> search p50 0.77ms

  target≈4,599 -> search p50 2.22ms

  target≈6,781 -> search p50 2.94ms

  target≈8,235 -> search p50 3.52ms

  target≈9,075 -> search p50 3.50ms

  target≈9,526 -> search p50 3.68ms
  -> |matches|≈6,622 ratio=0.66 balanced=False

{'size': 10000, 'k': 1000, 'window': 2000, 'matches_mean': 6621.875, 'balance_ratio': 0.66, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=10000 k/w=1000/2000 w=0 fields=none       hybrid_linear  p50=14.92ms qps=    65.3

n=10000 k/w=1000/2000 w=0 fields=none       hybrid_rrf     p50=15.12ms qps=    64.4

n=10000 k/w=1000/2000 w=0 fields=none       search_branch  p50=3.91ms qps=   252.4

n=10000 k/w=1000/2000 w=0 fields=none       vsim_branch    p50=5.69ms qps=   168.4

n=10000 k/w=1000/2000 w=0 fields=title+text hybrid_linear  p50=16.59ms qps=    58.6

n=10000 k/w=1000/2000 w=0 fields=title+text hybrid_rrf     p50=16.51ms qps=    59.2

n=10000 k/w=1000/2000 w=0 fields=title+text search_branch  p50=3.85ms qps=   256.2

n=10000 k/w=1000/2000 w=0 fields=title+text vsim_branch    p50=5.69ms qps=   170.7

n=10000 k/w=1000/2000 w=6 fields=none       hybrid_linear  p50=9.11ms qps=   107.4

n=10000 k/w=1000/2000 w=6 fields=none       hybrid_rrf     p50=9.10ms qps=   107.9

n=10000 k/w=1000/2000 w=6 fields=none       search_branch  p50=3.90ms qps=   253.2

n=10000 k/w=1000/2000 w=6 fields=none       vsim_branch    p50=5.64ms qps=   173.1

n=10000 k/w=1000/2000 w=6 fields=title+text hybrid_linear  p50=9.93ms qps=    98.5

n=10000 k/w=1000/2000 w=6 fields=title+text hybrid_rrf     p50=9.95ms qps=    97.8

n=10000 k/w=1000/2000 w=6 fields=title+text search_branch  p50=3.76ms qps=   262.2

n=10000 k/w=1000/2000 w=6 fields=title+text vsim_branch    p50=5.69ms qps=   171.4

===== balanced full, dataset size 100000 =====

loaded+indexed 100000 docs in 50.6s (hash_indexing_failures=0)

n=100000 k/w=10/20: vsim p50=0.25ms — calibrating
  target≈4,472 -> search p50 0.32ms
  target≈946 -> search p50 0.23ms
  -> |matches|≈1,689 ratio=0.92 balanced=True

{'size': 100000, 'k': 10, 'window': 20, 'matches_mean': 1689.3125, 'balance_ratio': 0.92, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=100000 k/w=10/20 w=0 fields=none       hybrid_linear  p50=0.54ms qps=  1728.6

n=100000 k/w=10/20 w=0 fields=none       hybrid_rrf     p50=0.47ms qps=  2011.3

n=100000 k/w=10/20 w=0 fields=none       search_branch  p50=0.23ms qps=  4015.8

n=100000 k/w=10/20 w=0 fields=none       vsim_branch    p50=0.25ms qps=  3904.8

n=100000 k/w=10/20 w=0 fields=title+text hybrid_linear  p50=0.56ms qps=  1693.6

n=100000 k/w=10/20 w=0 fields=title+text hybrid_rrf     p50=0.57ms qps=  1734.5

n=100000 k/w=10/20 w=0 fields=title+text search_branch  p50=0.38ms qps=  2526.2

n=100000 k/w=10/20 w=0 fields=title+text vsim_branch    p50=0.32ms qps=  3123.6

n=100000 k/w=10/20 w=6 fields=none       hybrid_linear  p50=0.39ms qps=  2402.8

n=100000 k/w=10/20 w=6 fields=none       hybrid_rrf     p50=0.45ms qps=  2130.5

n=100000 k/w=10/20 w=6 fields=none       search_branch  p50=0.23ms qps=  4070.7

n=100000 k/w=10/20 w=6 fields=none       vsim_branch    p50=0.24ms qps=  4232.3

n=100000 k/w=10/20 w=6 fields=title+text hybrid_linear  p50=0.50ms qps=  1896.5

n=100000 k/w=10/20 w=6 fields=title+text hybrid_rrf     p50=0.45ms qps=  2083.1

n=100000 k/w=10/20 w=6 fields=title+text search_branch  p50=0.34ms qps=  2752.4

n=100000 k/w=10/20 w=6 fields=title+text vsim_branch    p50=0.26ms qps=  3818.8
n=100000 k/w=100/200: vsim p50=0.71ms — calibrating

  target≈4,472 -> search p50 0.55ms

  target≈21,147 -> search p50 2.84ms

  target≈9,725 -> search p50 0.83ms
  -> |matches|≈15,858 ratio=1.16 balanced=True
{'size': 100000, 'k': 100, 'window': 200, 'matches_mean': 15857.53125, 'balance_ratio': 1.16, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=100000 k/w=100/200 w=0 fields=none       hybrid_linear  p50=2.31ms qps=   396.7

n=100000 k/w=100/200 w=0 fields=none       hybrid_rrf     p50=2.28ms qps=   403.7

n=100000 k/w=100/200 w=0 fields=none       search_branch  p50=0.92ms qps=   936.5

n=100000 k/w=100/200 w=0 fields=none       vsim_branch    p50=0.65ms qps=  1568.8

n=100000 k/w=100/200 w=0 fields=title+text hybrid_linear  p50=2.51ms qps=   365.8

n=100000 k/w=100/200 w=0 fields=title+text hybrid_rrf     p50=2.57ms qps=   359.6

n=100000 k/w=100/200 w=0 fields=title+text search_branch  p50=0.98ms qps=   892.5

n=100000 k/w=100/200 w=0 fields=title+text vsim_branch    p50=0.69ms qps=  1487.5

n=100000 k/w=100/200 w=6 fields=none       hybrid_linear  p50=1.66ms qps=   528.1

n=100000 k/w=100/200 w=6 fields=none       hybrid_rrf     p50=1.67ms qps=   526.6

n=100000 k/w=100/200 w=6 fields=none       search_branch  p50=0.91ms qps=   973.4

n=100000 k/w=100/200 w=6 fields=none       vsim_branch    p50=0.65ms qps=  1552.8

n=100000 k/w=100/200 w=6 fields=title+text hybrid_linear  p50=1.89ms qps=   469.0

n=100000 k/w=100/200 w=6 fields=title+text hybrid_rrf     p50=1.85ms qps=   475.6

n=100000 k/w=100/200 w=6 fields=title+text search_branch  p50=0.98ms qps=   908.5

n=100000 k/w=100/200 w=6 fields=title+text vsim_branch    p50=0.70ms qps=  1451.8

n=100000 k/w=1000/2000: vsim p50=8.36ms — calibrating

  target≈4,472 -> search p50 1.43ms

  target≈21,147 -> search p50 6.69ms
  -> |matches|≈27,422 ratio=0.80 balanced=True

{'size': 100000, 'k': 1000, 'window': 2000, 'matches_mean': 27421.6875, 'balance_ratio': 0.8, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=100000 k/w=1000/2000 w=0 fields=none       hybrid_linear  p50=22.70ms qps=    43.1

n=100000 k/w=1000/2000 w=0 fields=none       hybrid_rrf     p50=21.72ms qps=    44.8

n=100000 k/w=1000/2000 w=0 fields=none       search_branch  p50=5.91ms qps=   149.3

n=100000 k/w=1000/2000 w=0 fields=none       vsim_branch    p50=8.11ms qps=   123.8

n=100000 k/w=1000/2000 w=0 fields=title+text hybrid_linear  p50=24.62ms qps=    39.9

n=100000 k/w=1000/2000 w=0 fields=title+text hybrid_rrf     p50=23.66ms qps=    41.3

n=100000 k/w=1000/2000 w=0 fields=title+text search_branch  p50=6.01ms qps=   147.2

n=100000 k/w=1000/2000 w=0 fields=title+text vsim_branch    p50=8.23ms qps=   122.0

n=100000 k/w=1000/2000 w=6 fields=none       hybrid_linear  p50=12.94ms qps=    73.6

n=100000 k/w=1000/2000 w=6 fields=none       hybrid_rrf     p50=13.10ms qps=    72.7

n=100000 k/w=1000/2000 w=6 fields=none       search_branch  p50=6.09ms qps=   146.3

n=100000 k/w=1000/2000 w=6 fields=none       vsim_branch    p50=8.19ms qps=   123.0

n=100000 k/w=1000/2000 w=6 fields=title+text hybrid_linear  p50=14.56ms qps=    66.2

n=100000 k/w=1000/2000 w=6 fields=title+text hybrid_rrf     p50=14.90ms qps=    65.1

n=100000 k/w=1000/2000 w=6 fields=title+text search_branch  p50=6.34ms qps=   139.2

n=100000 k/w=1000/2000 w=6 fields=title+text vsim_branch    p50=8.47ms qps=   118.3

===== balanced full, dataset size 500000 =====

loaded+indexed 500000 docs in 451.1s (hash_indexing_failures=0)

n=500000 k/w=10/20: vsim p50=0.28ms — calibrating

  target≈10,000 -> search p50 1.21ms
  target≈1,414 -> search p50 0.40ms

  target≈532 -> search p50 0.22ms
  target≈867 -> search p50 0.52ms

  target≈679 -> search p50 0.26ms
  -> |matches|≈1,126 ratio=0.94 balanced=True
{'size': 500000, 'k': 10, 'window': 20, 'matches_mean': 1126.5, 'balance_ratio': 0.94, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=500000 k/w=10/20 w=0 fields=none       hybrid_linear  p50=0.50ms qps=  1921.5

n=500000 k/w=10/20 w=0 fields=none       hybrid_rrf     p50=0.53ms qps=  1809.1

n=500000 k/w=10/20 w=0 fields=none       search_branch  p50=0.23ms qps=  4116.1

n=500000 k/w=10/20 w=0 fields=none       vsim_branch    p50=0.23ms qps=  4364.0

n=500000 k/w=10/20 w=0 fields=title+text hybrid_linear  p50=0.59ms qps=  1625.3

n=500000 k/w=10/20 w=0 fields=title+text hybrid_rrf     p50=0.53ms qps=  1810.9

n=500000 k/w=10/20 w=0 fields=title+text search_branch  p50=0.31ms qps=  3020.1

n=500000 k/w=10/20 w=0 fields=title+text vsim_branch    p50=0.29ms qps=  3431.5

n=500000 k/w=10/20 w=6 fields=none       hybrid_linear  p50=0.38ms qps=  2453.5

n=500000 k/w=10/20 w=6 fields=none       hybrid_rrf     p50=0.42ms qps=  2325.1

n=500000 k/w=10/20 w=6 fields=none       search_branch  p50=0.21ms qps=  4459.9

n=500000 k/w=10/20 w=6 fields=none       vsim_branch    p50=0.23ms qps=  4336.9

n=500000 k/w=10/20 w=6 fields=title+text hybrid_linear  p50=0.41ms qps=  2279.2

n=500000 k/w=10/20 w=6 fields=title+text hybrid_rrf     p50=0.45ms qps=  2136.0

n=500000 k/w=10/20 w=6 fields=title+text search_branch  p50=0.28ms qps=  3416.0

n=500000 k/w=10/20 w=6 fields=title+text vsim_branch    p50=0.34ms qps=  2932.2
n=500000 k/w=100/200: vsim p50=0.77ms — calibrating

  target≈10,000 -> search p50 1.52ms
  target≈1,414 -> search p50 0.55ms

  target≈3,761 -> search p50 0.81ms
  -> |matches|≈4,828 ratio=1.06 balanced=True
{'size': 500000, 'k': 100, 'window': 200, 'matches_mean': 4827.9375, 'balance_ratio': 1.06, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=500000 k/w=100/200 w=0 fields=none       hybrid_linear  p50=2.30ms qps=   420.5

n=500000 k/w=100/200 w=0 fields=none       hybrid_rrf     p50=2.30ms qps=   419.9

n=500000 k/w=100/200 w=0 fields=none       search_branch  p50=0.87ms qps=  1084.3

n=500000 k/w=100/200 w=0 fields=none       vsim_branch    p50=0.75ms qps=  1359.9

n=500000 k/w=100/200 w=0 fields=title+text hybrid_linear  p50=2.44ms qps=   396.3

n=500000 k/w=100/200 w=0 fields=title+text hybrid_rrf     p50=2.48ms qps=   390.1

n=500000 k/w=100/200 w=0 fields=title+text search_branch  p50=0.93ms qps=  1012.3

n=500000 k/w=100/200 w=0 fields=title+text vsim_branch    p50=0.81ms qps=  1262.9

n=500000 k/w=100/200 w=6 fields=none       hybrid_linear  p50=1.60ms qps=   591.9

n=500000 k/w=100/200 w=6 fields=none       hybrid_rrf     p50=1.63ms qps=   580.7

n=500000 k/w=100/200 w=6 fields=none       search_branch  p50=0.84ms qps=  1108.9

n=500000 k/w=100/200 w=6 fields=none       vsim_branch    p50=0.77ms qps=  1327.8

n=500000 k/w=100/200 w=6 fields=title+text hybrid_linear  p50=1.77ms qps=   534.2

n=500000 k/w=100/200 w=6 fields=title+text hybrid_rrf     p50=1.76ms qps=   537.3

n=500000 k/w=100/200 w=6 fields=title+text search_branch  p50=1.01ms qps=   951.3

n=500000 k/w=100/200 w=6 fields=title+text vsim_branch    p50=0.86ms qps=  1184.4

n=500000 k/w=1000/2000: vsim p50=8.71ms — calibrating

  target≈10,000 -> search p50 4.73ms

  target≈70,711 -> search p50 20.16ms

  target≈26,591 -> search p50 4.40ms

  target≈43,362 -> search p50 7.21ms
  -> |matches|≈53,043 ratio=0.83 balanced=True

{'size': 500000, 'k': 1000, 'window': 2000, 'matches_mean': 53043.09375, 'balance_ratio': 0.83, 'gate_linear': '16/16', 'gate_rrf': '16/16'}

n=500000 k/w=1000/2000 w=0 fields=none       hybrid_linear  p50=25.07ms qps=    38.4

n=500000 k/w=1000/2000 w=0 fields=none       hybrid_rrf     p50=24.50ms qps=    39.1

n=500000 k/w=1000/2000 w=0 fields=none       search_branch  p50=7.21ms qps=   115.4

n=500000 k/w=1000/2000 w=0 fields=none       vsim_branch    p50=8.99ms qps=   112.6

n=500000 k/w=1000/2000 w=0 fields=title+text hybrid_linear  p50=26.83ms qps=    36.1

n=500000 k/w=1000/2000 w=0 fields=title+text hybrid_rrf     p50=26.89ms qps=    36.0

n=500000 k/w=1000/2000 w=0 fields=title+text search_branch  p50=7.55ms qps=   109.5

n=500000 k/w=1000/2000 w=0 fields=title+text vsim_branch    p50=9.06ms qps=   111.9

n=500000 k/w=1000/2000 w=6 fields=none       hybrid_linear  p50=14.88ms qps=    62.4

n=500000 k/w=1000/2000 w=6 fields=none       hybrid_rrf     p50=14.69ms qps=    62.9

n=500000 k/w=1000/2000 w=6 fields=none       search_branch  p50=7.11ms qps=   116.8

n=500000 k/w=1000/2000 w=6 fields=none       vsim_branch    p50=8.90ms qps=   114.2

n=500000 k/w=1000/2000 w=6 fields=title+text hybrid_linear  p50=17.37ms qps=    54.6

n=500000 k/w=1000/2000 w=6 fields=title+text hybrid_rrf     p50=17.82ms qps=    52.9

n=500000 k/w=1000/2000 w=6 fields=title+text search_branch  p50=7.85ms qps=   105.4

n=500000 k/w=1000/2000 w=6 fields=title+text vsim_branch    p50=8.84ms qps=   115.1
saved results_balanced_full.json / .csv

## Calibration & gates

`balance_ratio` = search p50 / vsim p50 at calibration (1.0 = perfect balance; a cell counts as balanced within ±20%).

In [2]:
pd.DataFrame(gates)

     size     k  window  matches_mean  balance_ratio gate_linear gate_rrf
0   10000    10      20    2469.37500           1.08       16/16    16/16
1   10000   100     200    2469.37500           1.07       16/16    16/16
2   10000  1000    2000    6621.87500           0.66       16/16    16/16
3  100000    10      20    1689.31250           0.92       16/16    16/16
4  100000   100     200   15857.53125           1.16       16/16    16/16
5  100000  1000    2000   27421.68750           0.80       16/16    16/16
6  500000    10      20    1126.50000           0.94       16/16    16/16
7  500000   100     200    4827.93750           1.06       16/16    16/16
8  500000  1000    2000   53043.09375           0.83       16/16    16/16

## p50 latency (ms)

In [3]:
df = pd.DataFrame(results)
pivot = df.pivot_table(index=['size', 'window', 'workers', 'fields'], columns='contender',
                       values='p50_ms', sort=False).round(2)
pivot[['hybrid_linear', 'hybrid_rrf', 'search_branch', 'vsim_branch']]

contender                         hybrid_linear  hybrid_rrf  search_branch  \
size   window workers fields
10000  20     0       none                 0.53        0.48           0.29
                      title+text           0.57        0.55           0.30
              6       none                 0.39        0.42           0.30
                      title+text           0.51        0.42           0.36
       200    0       none                 1.42        1.44           0.45
                      title+text           1.46        1.54           0.51
              6       none                 1.01        1.01           0.46
                      title+text           1.17        1.16           0.50
       2000   0       none                14.92       15.12           3.91
                      title+text          16.59       16.51           3.85
              6       none                 9.11        9.10           3.90
                      title+text           9.93        9.95           3.76
100000 20     0       none                 0.54        0.47           0.23
                      title+text           0.56        0.57           0.38
              6       none                 0.39        0.45           0.23
                      title+text           0.50        0.45           0.34
       200    0       none                 2.31        2.28           0.92
                      title+text           2.51        2.57           0.98
              6       none                 1.66        1.67           0.91
                      title+text           1.89        1.85           0.98
       2000   0       none                22.70       21.72           5.91
                      title+text          24.62       23.66           6.01
              6       none                12.94       13.10           6.09
                      title+text          14.56       14.90           6.34
500000 20     0       none                 0.50        0.53           0.23
                      title+text           0.59        0.53           0.31
              6       none                 0.38        0.42           0.21
                      title+text           0.41        0.45           0.28
       200    0       none                 2.30        2.30           0.87
                      title+text           2.44        2.48           0.93
              6       none                 1.60        1.63           0.84
                      title+text           1.77        1.76           1.01
       2000   0       none                25.07       24.50           7.21
                      title+text          26.83       26.89           7.55
              6       none                14.88       14.69           7.11
                      title+text          17.37       17.82           7.85

contender                         vsim_branch
size   window workers fields
10000  20     0       none               0.15
                      title+text         0.25
              6       none               0.17
                      title+text         0.21
       200    0       none               0.43
                      title+text         0.47
              6       none               0.37
                      title+text         0.43
       2000   0       none               5.69
                      title+text         5.69
              6       none               5.64
                      title+text         5.69
100000 20     0       none               0.25
                      title+text         0.32
              6       none               0.24
                      title+text         0.26
       200    0       none               0.65
                      title+text         0.69
              6       none               0.65
                      title+text         0.70
       2000   0       none               8.11
                      title+text         8.23
              6       none               8.19
                      title+text         8.47
500000 20     0       none               0.23
                      title+text         0.29
              6       none               0.23
                      title+text         0.34
       200    0       none               0.75
                      title+text         0.81
              6       none               0.77
                      title+text         0.86
       2000   0       none               8.99
                      title+text         9.06
              6       none               8.90
                      title+text         8.84

## C — the serial overhead, and the C(WINDOW) curve

fields=none. `C_w0 = hybrid − (search+vsim)`, `C_w6 = hybrid − max(search,vsim)`
(mean latency). If depletion truly overlaps and C is genuinely serial, the two agree.
`C/max` says how the overhead compares to running one entire branch.

In [4]:
m = df[df.fields == 'none'].pivot_table(index=['size', 'window', 'workers'],
        columns='contender', values='mean_ms', sort=False)
mx = m[['search_branch', 'vsim_branch']].max(axis=1)
sm = m[['search_branch', 'vsim_branch']].sum(axis=1)
c = pd.DataFrame({'hybrid': m['hybrid_linear'], 'max_branch': mx, 'sum_branch': sm})
c['C_ms'] = (c['hybrid'] - c['sum_branch']).where(
    c.index.get_level_values('workers') == 0, c['hybrid'] - c['max_branch'])
c['C_pct_of_max'] = (100 * c['C_ms'] / c['max_branch'])
c['gain_hint'] = None
c.round(2)

                       hybrid  max_branch  sum_branch  C_ms  C_pct_of_max  \
size   window workers
10000  20     0          0.55        0.32        0.47  0.08         24.39
              6          0.40        0.32        0.50  0.08         24.66
       200    0          1.45        0.47        0.90  0.55        116.76
              6          1.04        0.51        0.88  0.53        105.14
       2000   0         15.31        5.94        9.90  5.41         91.02
              6          9.31        5.78        9.73  3.53         61.16
100000 20     0          0.58        0.26        0.51  0.07         28.66
              6          0.42        0.25        0.48  0.17         69.42
       200    0          2.52        1.07        1.71  0.82         76.38
              6          1.89        1.03        1.67  0.87         84.33
       2000   0         23.19        8.08       14.78  8.42        104.20
              6         13.59        8.13       14.96  5.46         67.15
500000 20     0          0.52        0.24        0.47  0.05         19.90
              6          0.41        0.23        0.45  0.18         76.76
       200    0          2.38        0.92        1.66  0.72         78.14
              6          1.69        0.90        1.65  0.79         87.34
       2000   0         26.03        8.88       17.55  8.48         95.53
              6         16.04        8.75       17.31  7.28         83.17

                      gain_hint
size   window workers
10000  20     0            None
              6            None
       200    0            None
              6            None
       2000   0            None
              6            None
100000 20     0            None
              6            None
       200    0            None
              6            None
       2000   0            None
              6            None
500000 20     0            None
              6            None
       200    0            None
              6            None
       2000   0            None
              6            None

### Parallelism gain per depth (`p50(w0)/p50(w6)`, fields=none)

In [5]:
p = df[df.fields == 'none'].pivot_table(index=['size', 'window', 'contender'],
        columns='workers', values='p50_ms', sort=False)
p.columns = [f'w{c}' for c in p.columns]
p['gain'] = (p['w0'] / p['w6']).round(2)
p.round(2)

                                w0     w6  gain
size   window contender
10000  20     hybrid_linear   0.53   0.39  1.35
              hybrid_rrf      0.48   0.42  1.12
              search_branch   0.29   0.30  0.98
              vsim_branch     0.15   0.17  0.91
       200    hybrid_linear   1.42   1.01  1.40
              hybrid_rrf      1.44   1.01  1.42
              search_branch   0.45   0.46  0.96
              vsim_branch     0.43   0.37  1.16
       2000   hybrid_linear  14.92   9.11  1.64
              hybrid_rrf     15.12   9.10  1.66
              search_branch   3.91   3.90  1.00
              vsim_branch     5.69   5.64  1.01
100000 20     hybrid_linear   0.54   0.39  1.39
              hybrid_rrf      0.47   0.45  1.03
              search_branch   0.23   0.23  0.97
              vsim_branch     0.25   0.24  1.05
       200    hybrid_linear   2.31   1.66  1.39
              hybrid_rrf      2.28   1.67  1.37
              search_branch   0.92   0.91  1.00
              vsim_branch     0.65   0.65  0.99
       2000   hybrid_linear  22.70  12.94  1.75
              hybrid_rrf     21.72  13.10  1.66
              search_branch   5.91   6.09  0.97
              vsim_branch     8.11   8.19  0.99
500000 20     hybrid_linear   0.50   0.38  1.33
              hybrid_rrf      0.53   0.42  1.28
              search_branch   0.23   0.21  1.10
              vsim_branch     0.23   0.23  0.99
       200    hybrid_linear   2.30   1.60  1.44
              hybrid_rrf      2.30   1.63  1.42
              search_branch   0.87   0.84  1.03
              vsim_branch     0.75   0.77  0.98
       2000   hybrid_linear  25.07  14.88  1.68
              hybrid_rrf     24.50  14.69  1.67
              search_branch   7.21   7.11  1.01
              vsim_branch     8.99   8.90  1.01